/* A recursive-descent parser generated by peg 0.1.18 */

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef __cplusplus
  #include <vector>
#endif
#define YYRULECOUNT 38
#line 20 "src/leg.leg"

# include "tree.h"
# include "version.h"

# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <string.h>
# include <libgen.h>
# include <assert.h>

  typedef struct Header Header;

  struct Header {
    int	    line;
    char   *text;
    Header *next;
  };

  FILE *input= 0;

  int   verboseFlag= 0;
  int   nolinesFlag= 0;

  static int	 lineNumber= 0;
  static int	 headerLine= 0;
  static int	 actionLine= 0;
  static char	*fileName= 0;
  static int	 trailerLine= 0;
  static char	*trailer= 0;
  static Header	*headers= 0;

  void makeHeader(int line, char *text);
  void makeTrailer(int line, char *text);

  void yyerror(char *message);

# define YY_INPUT(buf, result, max)			\
  {							\
    int c= getc(input);					\
    /* if ('\n' == c || '\r' == c) ++lineNumber; */	\
    result= (EOF == c) ? 0 : (*(buf)= c, 1);		\
  }

# define YY_LOCAL(T)	static T
# define YY_RULE(T)	static T

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->_begin= yy->_pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->_end= yy->_pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *_buf;
  int       _buflen;
  int       _pos;
  int       _limit;
  int       _maxpos;
  char     *_text;
  int       _textlen;
  int       _begin;
  int       _end;
  int       _textmax;
  yythunk  *_thunks;
  int       _thunkslen;
  int       _thunkpos;
  YYSTYPE   _;
  YYSTYPE  *_val;
#ifdef __cplusplus
  std::vector<YYSTYPE>* _vals;
#else
  YYSTYPE  *_vals;
  int       _valslen;
#endif
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext yyctx_= { 0, 0 };
yycontext *yyctx= &yyctx_;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->_buflen - yy->_pos < 512)
    {
      yy->_buflen *= 2;
      yy->_buf= (char *)YY_REALLOC(yy, yy->_buf, yy->_buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->_buf + yy->_pos), yyn, (yy->_buflen - yy->_pos));
#else
  YY_INPUT((yy->_buf + yy->_pos), yyn, (yy->_buflen - yy->_pos));
#endif
  if (!yyn) return 0;
  yy->_limit += yyn;
  return 1;
}

YY_LOCAL(void) yyrecordMaxPos(yycontext *yy)
{
  if (yy->_pos > yy->_maxpos) {
    yy->_maxpos = yy->_pos;
    yyprintf((stderr, "       maxpos=%d [after '%c']\n", yy->_maxpos, yy->_buf[yy->_maxpos-1]));
  }
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->_pos >= yy->_limit && !yyrefill(yy)) return 0;
  ++yy->_pos;
  yyrecordMaxPos(yy);
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->_pos >= yy->_limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->_buf[yy->_pos] == c)
    {
      ++yy->_pos;
      yyrecordMaxPos(yy);
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->_buf+yy->_pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->_buf+yy->_pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->_pos;
  while (*s)
    {
      if (yy->_pos >= yy->_limit && !yyrefill(yy)) return 0;
      if (yy->_buf[yy->_pos] != *s)
	{
	  yy->_pos= yysav;
	  return 0;
	}
      ++s;
      ++yy->_pos;
    }
  yyrecordMaxPos(yy);
  return 1;
}

YY_LOCAL(int) yymatchIString(yycontext *yy, const char *s)
{
  int yysav= yy->_pos;
  while (*s)
    {
      if (yy->_pos >= yy->_limit && !yyrefill(yy)) return 0;
      if (tolower(yy->_buf[yy->_pos]) != *s)
        {
          yy->_pos= yysav;
          return 0;
        }
      ++s;
      ++yy->_pos;
    }
  yyrecordMaxPos(yy);
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->_pos >= yy->_limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->_buf[yy->_pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->_pos;
      yyrecordMaxPos(yy);
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->_buf+yy->_pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->_buf+yy->_pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->_thunkpos >= yy->_thunkslen)
    {
      yy->_thunkslen *= 2;
      yy->_thunks= (yythunk *)YY_REALLOC(yy, yy->_thunks, sizeof(yythunk) * yy->_thunkslen);
    }
  yy->_thunks[yy->_thunkpos].begin=  begin;
  yy->_thunks[yy->_thunkpos].end=    end;
  yy->_thunks[yy->_thunkpos].action= action;
  ++yy->_thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->_textlen < (yyleng + 1))
	{
	  yy->_textlen *= 2;
	  yy->_text= (char *)YY_REALLOC(yy, yy->_text, yy->_textlen);
	}
      memcpy(yy->_text, yy->_buf + begin, yyleng);
    }
  yy->_text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->_thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->_thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->_text));
      thunk->action(yy, yy->_text, yyleng);
    }
  yy->_thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->_limit -= yy->_pos))
    {
      memmove(yy->_buf, yy->_buf + yy->_pos, yy->_limit);
    }
  yy->_begin -= yy->_pos;
  yy->_end -= yy->_pos;
  yy->_pos= yy->_thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
#ifdef __cplusplus
  yy->_vals->resize(yy->_vals->size() + count);
  yy->_val = &yy->_vals->back();
#else
  yy->_val += count;
  while (yy->_valslen <= yy->_val - yy->_vals)
    {
      long offset= yy->_val - yy->_vals;
      size_t oldlen = yy->_valslen;
      yy->_valslen *= 2;
      yy->_vals= (YYSTYPE *)YY_REALLOC(yy, yy->_vals, sizeof(YYSTYPE) * yy->_valslen);
      memset(&yy->_vals[oldlen], 0, sizeof(YYSTYPE) * oldlen);
      yy->_val= yy->_vals + offset;
    }
#endif
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)
{
#ifdef __cplusplus
  yy->_vals->resize(yy->_vals->size() - count);
  yy->_val = &yy->_vals->back();
#else
  yy->_val -= count;
#endif
}
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->_val[count]= yy->_; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_comment(yycontext *yy); /* 38 */
YY_RULE(int) yy_space(yycontext *yy); /* 37 */
YY_RULE(int) yy_braces(yycontext *yy); /* 36 */
YY_RULE(int) yy_range(yycontext *yy); /* 35 */
YY_RULE(int) yy_END(yycontext *yy); /* 34 */
YY_RULE(int) yy_BEGIN(yycontext *yy); /* 33 */
YY_RULE(int) yy_DOT(yycontext *yy); /* 32 */
YY_RULE(int) yy_class(yycontext *yy); /* 31 */
YY_RULE(int) yy_char(yycontext *yy); /* 30 */
YY_RULE(int) yy_CLOSE(yycontext *yy); /* 29 */
YY_RULE(int) yy_OPEN(yycontext *yy); /* 28 */
YY_RULE(int) yy_COLON(yycontext *yy); /* 27 */
YY_RULE(int) yy_PLUS(yycontext *yy); /* 26 */
YY_RULE(int) yy_STAR(yycontext *yy); /* 25 */
YY_RULE(int) yy_QUESTION(yycontext *yy); /* 24 */
YY_RULE(int) yy_primary(yycontext *yy); /* 23 */
YY_RULE(int) yy_NOT(yycontext *yy); /* 22 */
YY_RULE(int) yy_suffix(yycontext *yy); /* 21 */
YY_RULE(int) yy_AND(yycontext *yy); /* 20 */
YY_RULE(int) yy_AT(yycontext *yy); /* 19 */
YY_RULE(int) yy_action(yycontext *yy); /* 18 */
YY_RULE(int) yy_TILDE(yycontext *yy); /* 17 */
YY_RULE(int) yy_prefix(yycontext *yy); /* 16 */
YY_RULE(int) yy_error(yycontext *yy); /* 15 */
YY_RULE(int) yy_BAR(yycontext *yy); /* 14 */
YY_RULE(int) yy_sequence(yycontext *yy); /* 13 */
YY_RULE(int) yy_SEMICOLON(yycontext *yy); /* 12 */
YY_RULE(int) yy_expression(yycontext *yy); /* 11 */
YY_RULE(int) yy_EQUAL(yycontext *yy); /* 10 */
YY_RULE(int) yy_identifier(yycontext *yy); /* 9 */
YY_RULE(int) yy_RPERCENT(yycontext *yy); /* 8 */
YY_RULE(int) yy_end_of_line(yycontext *yy); /* 7 */
YY_RULE(int) yy_end_of_file(yycontext *yy); /* 6 */
YY_RULE(int) yy_trailer(yycontext *yy); /* 5 */
YY_RULE(int) yy_definition(yycontext *yy); /* 4 */
YY_RULE(int) yy_declaration(yycontext *yy); /* 3 */
YY_RULE(int) yy_(yycontext *yy); /* 2 */
YY_RULE(int) yy_grammar(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_end_of_line(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_end_of_line\n"));
  {
#line 160
   ++lineNumber ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_action(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_action\n"));
  {
#line 133
   actionLine= lineNumber ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_12_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_12_primary\n"));
  {
#line 116
   push(makePredicate("YY_END")); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_11_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_11_primary\n"));
  {
#line 115
   push(makePredicate("YY_BEGIN")); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_10_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_10_primary\n"));
  {
#line 114
   push(makeAction(actionLine, yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_9_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_9_primary\n"));
  {
#line 113
   push(makeDot()); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_8_primary\n"));
  {
#line 112
   push(makeClass(yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_7_primary\n"));
  {
#line 111
   push(makeString(yytext, 1, 0)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_6_primary\n"));
  {
#line 110
   push(makeString(yytext, 0, 0)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_5_primary\n"));
  {
#line 109
   push(makeString(yytext, 1, 1)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_4_primary\n"));
  {
#line 108
   push(makeString(yytext, 0, 1)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_3_primary\n"));
  {
#line 106
   push(makeName(findRule(yytext))); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_2_primary\n"));
  {
#line 105
   Node *name= makeName(findRule(yytext));  name->name.variable= pop();  push(name); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_primary(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_primary\n"));
  {
#line 104
   push(makeVariable(yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_suffix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_3_suffix\n"));
  {
#line 101
   push(makePlus (pop())); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_suffix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_2_suffix\n"));
  {
#line 100
   push(makeStar (pop())); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_suffix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_suffix\n"));
  {
#line 99
   push(makeQuery(pop())); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_4_prefix\n"));
  {
#line 96
   push(makePeekNot(pop())); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_3_prefix\n"));
  {
#line 95
   push(makePeekFor(pop())); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_2_prefix\n"));
  {
#line 94
   push(makePredicate(yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_prefix(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_prefix\n"));
  {
#line 93
   push(makeInline(yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_error(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_error\n"));
  {
#line 90
   push(makeError(pop(), yytext)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_sequence(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_sequence\n"));
  {
#line 87
   Node *f= pop();  push(Sequence_append(pop(), f)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_expression(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_expression\n"));
  {
#line 84
   Node *f= pop();  push(Alternate_append(pop(), f)); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_definition(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_2_definition\n"));
  {
#line 81
   Node *e= pop();  Rule_setExpression(pop(), e); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_definition(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_definition\n"));
  {
#line 79
   if (push(beginRule(findRule(yytext)))->rule.expression)
							    fprintf(stderr, "rule '%s' redefined\n", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_trailer(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_2_trailer\n"));
  {
#line 77
   makeTrailer(headerLine, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_trailer(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_trailer\n"));
  {
#line 76
   headerLine= lineNumber ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_declaration(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_2_declaration\n"));
  {
#line 74
   makeHeader(headerLine, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_declaration(yycontext *yy, char *yytext, int yyleng)
{
#define y_ yy->_
#define yypos yy->_pos
#define yythunkpos yy->_thunkpos
  yyprintf((stderr, "do yy_1_declaration\n"));
  {
#line 72
   headerLine= lineNumber; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_comment(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "comment"));  if (!yymatchChar(yy, '#')) goto l1;
  l2:;	
  {  int yypos3= yy->_pos, yythunkpos3= yy->_thunkpos;
  {  int yypos4= yy->_pos, yythunkpos4= yy->_thunkpos;  int yymaxpos4= yy->_maxpos;  if (!yy_end_of_line(yy)) goto l4;  yy->_maxpos= yymaxpos4;  goto l3;
  l4:;	  yy->_pos= yypos4; yy->_thunkpos= yythunkpos4;  yy->_maxpos= yymaxpos4;
  }  if (!yymatchDot(yy)) goto l3;  goto l2;
  l3:;	  yy->_pos= yypos3; yy->_thunkpos= yythunkpos3;
  }  if (!yy_end_of_line(yy)) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yy->_buf+yy->_pos));
  return 1;
  l1:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_space(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "space"));
  {  int yypos6= yy->_pos, yythunkpos6= yy->_thunkpos;  if (!yymatchChar(yy, ' ')) goto l7;  goto l6;
  l7:;	  yy->_pos= yypos6; yy->_thunkpos= yythunkpos6;  if (!yymatchChar(yy, '\t')) goto l8;  goto l6;
  l8:;	  yy->_pos= yypos6; yy->_thunkpos= yythunkpos6;  if (!yy_end_of_line(yy)) goto l5;
  }
  l6:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yy->_buf+yy->_pos));
  return 1;
  l5:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_braces(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "braces"));
  {  int yypos10= yy->_pos, yythunkpos10= yy->_thunkpos;  if (!yymatchChar(yy, '{')) goto l11;
  l12:;	
  {  int yypos13= yy->_pos, yythunkpos13= yy->_thunkpos;  if (!yy_braces(yy)) goto l13;  goto l12;
  l13:;	  yy->_pos= yypos13; yy->_thunkpos= yythunkpos13;
  }  if (!yymatchChar(yy, '}')) goto l11;  goto l10;
  l11:;	  yy->_pos= yypos10; yy->_thunkpos= yythunkpos10;
  {  int yypos14= yy->_pos, yythunkpos14= yy->_thunkpos;  int yymaxpos14= yy->_maxpos;  if (!yymatchChar(yy, '}')) goto l14;  yy->_maxpos= yymaxpos14;  goto l9;
  l14:;	  yy->_pos= yypos14; yy->_thunkpos= yythunkpos14;  yy->_maxpos= yymaxpos14;
  }
  {  int yypos15= yy->_pos, yythunkpos15= yy->_thunkpos;  if (!yy_end_of_line(yy)) goto l16;  goto l15;
  l16:;	  yy->_pos= yypos15; yy->_thunkpos= yythunkpos15;  if (!yymatchDot(yy)) goto l9;
  }
  l15:;	
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "braces", yy->_buf+yy->_pos));
  return 1;
  l9:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "braces", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_range(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "range"));
  {  int yypos18= yy->_pos, yythunkpos18= yy->_thunkpos;  if (!yy_char(yy)) goto l19;  if (!yymatchChar(yy, '-')) goto l19;  if (!yy_char(yy)) goto l19;  goto l18;
  l19:;	  yy->_pos= yypos18; yy->_thunkpos= yythunkpos18;  if (!yy_char(yy)) goto l17;
  }
  l18:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "range", yy->_buf+yy->_pos));
  return 1;
  l17:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "range", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_END(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "END"));  if (!yymatchChar(yy, '>')) goto l20;  if (!yy_(yy)) goto l20;
  yyprintf((stderr, "  ok   %s @ %s\n", "END", yy->_buf+yy->_pos));
  return 1;
  l20:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "END", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_BEGIN(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "BEGIN"));  if (!yymatchChar(yy, '<')) goto l21;  if (!yy_(yy)) goto l21;
  yyprintf((stderr, "  ok   %s @ %s\n", "BEGIN", yy->_buf+yy->_pos));
  return 1;
  l21:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BEGIN", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_DOT(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "DOT"));  if (!yymatchChar(yy, '.')) goto l22;  if (!yy_(yy)) goto l22;
  yyprintf((stderr, "  ok   %s @ %s\n", "DOT", yy->_buf+yy->_pos));
  return 1;
  l22:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DOT", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_class(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "class"));  if (!yymatchChar(yy, '[')) goto l23;  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l23;
#undef yytext
#undef yyleng
  }
  l24:;	
  {  int yypos25= yy->_pos, yythunkpos25= yy->_thunkpos;
  {  int yypos26= yy->_pos, yythunkpos26= yy->_thunkpos;  int yymaxpos26= yy->_maxpos;  if (!yymatchChar(yy, ']')) goto l26;  yy->_maxpos= yymaxpos26;  goto l25;
  l26:;	  yy->_pos= yypos26; yy->_thunkpos= yythunkpos26;  yy->_maxpos= yymaxpos26;
  }  if (!yy_range(yy)) goto l25;  goto l24;
  l25:;	  yy->_pos= yypos25; yy->_thunkpos= yythunkpos25;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l23;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, ']')) goto l23;  if (!yy_(yy)) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "class", yy->_buf+yy->_pos));
  return 1;
  l23:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "class", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_char(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "char"));
  {  int yypos28= yy->_pos, yythunkpos28= yy->_thunkpos;  if (!yymatchChar(yy, '\\')) goto l29;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\204\040\000\000\000\000\000\070\146\100\124\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l29;  goto l28;
  l29:;	  yy->_pos= yypos28; yy->_thunkpos= yythunkpos28;  if (!yymatchChar(yy, '\\')) goto l30;  if (!yymatchChar(yy, 'x')) goto l30;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l30;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l30;  goto l28;
  l30:;	  yy->_pos= yypos28; yy->_thunkpos= yythunkpos28;  if (!yymatchChar(yy, '\\')) goto l31;  if (!yymatchChar(yy, 'x')) goto l31;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l31;  goto l28;
  l31:;	  yy->_pos= yypos28; yy->_thunkpos= yythunkpos28;  if (!yymatchChar(yy, '\\')) goto l32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\017\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l32;  goto l28;
  l32:;	  yy->_pos= yypos28; yy->_thunkpos= yythunkpos28;  if (!yymatchChar(yy, '\\')) goto l33;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l33;
  {  int yypos34= yy->_pos, yythunkpos34= yy->_thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l34;  goto l35;
  l34:;	  yy->_pos= yypos34; yy->_thunkpos= yythunkpos34;
  }
  l35:;	  goto l28;
  l33:;	  yy->_pos= yypos28; yy->_thunkpos= yythunkpos28;
  {  int yypos36= yy->_pos, yythunkpos36= yy->_thunkpos;  int yymaxpos36= yy->_maxpos;  if (!yymatchChar(yy, '\\')) goto l36;  yy->_maxpos= yymaxpos36;  goto l27;
  l36:;	  yy->_pos= yypos36; yy->_thunkpos= yythunkpos36;  yy->_maxpos= yymaxpos36;
  }  if (!yymatchDot(yy)) goto l27;
  }
  l28:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "char", yy->_buf+yy->_pos));
  return 1;
  l27:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "char", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_CLOSE(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yymatchChar(yy, ')')) goto l37;  if (!yy_(yy)) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", yy->_buf+yy->_pos));
  return 1;
  l37:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_OPEN(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yymatchChar(yy, '(')) goto l38;  if (!yy_(yy)) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", yy->_buf+yy->_pos));
  return 1;
  l38:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_COLON(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchChar(yy, ':')) goto l39;  if (!yy_(yy)) goto l39;
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", yy->_buf+yy->_pos));
  return 1;
  l39:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_PLUS(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar(yy, '+')) goto l40;  if (!yy_(yy)) goto l40;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yy->_buf+yy->_pos));
  return 1;
  l40:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_STAR(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "STAR"));  if (!yymatchChar(yy, '*')) goto l41;  if (!yy_(yy)) goto l41;
  yyprintf((stderr, "  ok   %s @ %s\n", "STAR", yy->_buf+yy->_pos));
  return 1;
  l41:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STAR", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_QUESTION(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "QUESTION"));  if (!yymatchChar(yy, '?')) goto l42;  if (!yy_(yy)) goto l42;
  yyprintf((stderr, "  ok   %s @ %s\n", "QUESTION", yy->_buf+yy->_pos));
  return 1;
  l42:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QUESTION", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_primary(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "primary"));
  {  int yypos44= yy->_pos, yythunkpos44= yy->_thunkpos;  if (!yy_identifier(yy)) goto l45;  yyDo(yy, yy_1_primary, yy->_begin, yy->_end);  if (!yy_COLON(yy)) goto l45;  if (!yy_identifier(yy)) goto l45;
  {  int yypos46= yy->_pos, yythunkpos46= yy->_thunkpos;  int yymaxpos46= yy->_maxpos;  if (!yy_EQUAL(yy)) goto l46;  yy->_maxpos= yymaxpos46;  goto l45;
  l46:;	  yy->_pos= yypos46; yy->_thunkpos= yythunkpos46;  yy->_maxpos= yymaxpos46;
  }  yyDo(yy, yy_2_primary, yy->_begin, yy->_end);  goto l44;
  l45:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_identifier(yy)) goto l47;
  {  int yypos48= yy->_pos, yythunkpos48= yy->_thunkpos;  int yymaxpos48= yy->_maxpos;  if (!yy_EQUAL(yy)) goto l48;  yy->_maxpos= yymaxpos48;  goto l47;
  l48:;	  yy->_pos= yypos48; yy->_thunkpos= yythunkpos48;  yy->_maxpos= yymaxpos48;
  }  yyDo(yy, yy_3_primary, yy->_begin, yy->_end);  goto l44;
  l47:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_OPEN(yy)) goto l49;  if (!yy_expression(yy)) goto l49;  if (!yy_CLOSE(yy)) goto l49;  goto l44;
  l49:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l50;
#undef yytext
#undef yyleng
  }
  l51:;	
  {  int yypos52= yy->_pos, yythunkpos52= yy->_thunkpos;
  {  int yypos53= yy->_pos, yythunkpos53= yy->_thunkpos;  int yymaxpos53= yy->_maxpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l53;  yy->_maxpos= yymaxpos53;  goto l52;
  l53:;	  yy->_pos= yypos53; yy->_thunkpos= yythunkpos53;  yy->_maxpos= yymaxpos53;
  }  if (!yy_char(yy)) goto l52;  goto l51;
  l52:;	  yy->_pos= yypos52; yy->_thunkpos= yythunkpos52;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l50;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;  if (!yy_(yy)) goto l50;  yyDo(yy, yy_4_primary, yy->_begin, yy->_end);  goto l44;
  l50:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l54;  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l54;
#undef yytext
#undef yyleng
  }
  l55:;	
  {  int yypos56= yy->_pos, yythunkpos56= yy->_thunkpos;
  {  int yypos57= yy->_pos, yythunkpos57= yy->_thunkpos;  int yymaxpos57= yy->_maxpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l57;  yy->_maxpos= yymaxpos57;  goto l56;
  l57:;	  yy->_pos= yypos57; yy->_thunkpos= yythunkpos57;  yy->_maxpos= yymaxpos57;
  }  if (!yy_char(yy)) goto l56;  goto l55;
  l56:;	  yy->_pos= yypos56; yy->_thunkpos= yythunkpos56;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l54;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l54;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l54;  if (!yy_(yy)) goto l54;  yyDo(yy, yy_5_primary, yy->_begin, yy->_end);  goto l44;
  l54:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l58;  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l58;
#undef yytext
#undef yyleng
  }
  l59:;	
  {  int yypos60= yy->_pos, yythunkpos60= yy->_thunkpos;
  {  int yypos61= yy->_pos, yythunkpos61= yy->_thunkpos;  int yymaxpos61= yy->_maxpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l61;  yy->_maxpos= yymaxpos61;  goto l60;
  l61:;	  yy->_pos= yypos61; yy->_thunkpos= yythunkpos61;  yy->_maxpos= yymaxpos61;
  }  if (!yy_char(yy)) goto l60;  goto l59;
  l60:;	  yy->_pos= yypos60; yy->_thunkpos= yythunkpos60;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l58;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l58;  if (!yy_(yy)) goto l58;  yyDo(yy, yy_6_primary, yy->_begin, yy->_end);  goto l44;
  l58:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l62;  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l62;
#undef yytext
#undef yyleng
  }
  l63:;	
  {  int yypos64= yy->_pos, yythunkpos64= yy->_thunkpos;
  {  int yypos65= yy->_pos, yythunkpos65= yy->_thunkpos;  int yymaxpos65= yy->_maxpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l65;  yy->_maxpos= yymaxpos65;  goto l64;
  l65:;	  yy->_pos= yypos65; yy->_thunkpos= yythunkpos65;  yy->_maxpos= yymaxpos65;
  }  if (!yy_char(yy)) goto l64;  goto l63;
  l64:;	  yy->_pos= yypos64; yy->_thunkpos= yythunkpos64;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l62;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l62;  if (!yy_(yy)) goto l62;  yyDo(yy, yy_7_primary, yy->_begin, yy->_end);  goto l44;
  l62:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_class(yy)) goto l66;  yyDo(yy, yy_8_primary, yy->_begin, yy->_end);  goto l44;
  l66:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_DOT(yy)) goto l67;  yyDo(yy, yy_9_primary, yy->_begin, yy->_end);  goto l44;
  l67:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_action(yy)) goto l68;  yyDo(yy, yy_10_primary, yy->_begin, yy->_end);  goto l44;
  l68:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_BEGIN(yy)) goto l69;  yyDo(yy, yy_11_primary, yy->_begin, yy->_end);  goto l44;
  l69:;	  yy->_pos= yypos44; yy->_thunkpos= yythunkpos44;  if (!yy_END(yy)) goto l43;  yyDo(yy, yy_12_primary, yy->_begin, yy->_end);
  }
  l44:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "primary", yy->_buf+yy->_pos));
  return 1;
  l43:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "primary", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_NOT(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "NOT"));  if (!yymatchChar(yy, '!')) goto l70;  if (!yy_(yy)) goto l70;
  yyprintf((stderr, "  ok   %s @ %s\n", "NOT", yy->_buf+yy->_pos));
  return 1;
  l70:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOT", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_suffix(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "suffix"));  if (!yy_primary(yy)) goto l71;
  {  int yypos72= yy->_pos, yythunkpos72= yy->_thunkpos;
  {  int yypos74= yy->_pos, yythunkpos74= yy->_thunkpos;  if (!yy_QUESTION(yy)) goto l75;  yyDo(yy, yy_1_suffix, yy->_begin, yy->_end);  goto l74;
  l75:;	  yy->_pos= yypos74; yy->_thunkpos= yythunkpos74;  if (!yy_STAR(yy)) goto l76;  yyDo(yy, yy_2_suffix, yy->_begin, yy->_end);  goto l74;
  l76:;	  yy->_pos= yypos74; yy->_thunkpos= yythunkpos74;  if (!yy_PLUS(yy)) goto l72;  yyDo(yy, yy_3_suffix, yy->_begin, yy->_end);
  }
  l74:;	  goto l73;
  l72:;	  yy->_pos= yypos72; yy->_thunkpos= yythunkpos72;
  }
  l73:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "suffix", yy->_buf+yy->_pos));
  return 1;
  l71:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "suffix", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_AND(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "AND"));  if (!yymatchChar(yy, '&')) goto l77;  if (!yy_(yy)) goto l77;
  yyprintf((stderr, "  ok   %s @ %s\n", "AND", yy->_buf+yy->_pos));
  return 1;
  l77:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AND", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_AT(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "AT"));  if (!yymatchChar(yy, '@')) goto l78;  if (!yy_(yy)) goto l78;
  yyprintf((stderr, "  ok   %s @ %s\n", "AT", yy->_buf+yy->_pos));
  return 1;
  l78:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AT", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_action(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "action"));  if (!yymatchChar(yy, '{')) goto l79;  yyDo(yy, yy_1_action, yy->_begin, yy->_end);  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l79;
#undef yytext
#undef yyleng
  }
  l80:;	
  {  int yypos81= yy->_pos, yythunkpos81= yy->_thunkpos;  if (!yy_braces(yy)) goto l81;  goto l80;
  l81:;	  yy->_pos= yypos81; yy->_thunkpos= yythunkpos81;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l79;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '}')) goto l79;  if (!yy_(yy)) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "action", yy->_buf+yy->_pos));
  return 1;
  l79:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "action", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_TILDE(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "TILDE"));  if (!yymatchChar(yy, '~')) goto l82;  if (!yy_(yy)) goto l82;
  yyprintf((stderr, "  ok   %s @ %s\n", "TILDE", yy->_buf+yy->_pos));
  return 1;
  l82:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TILDE", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_prefix(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "prefix"));
  {  int yypos84= yy->_pos, yythunkpos84= yy->_thunkpos;  if (!yy_AT(yy)) goto l85;  if (!yy_action(yy)) goto l85;  yyDo(yy, yy_1_prefix, yy->_begin, yy->_end);  goto l84;
  l85:;	  yy->_pos= yypos84; yy->_thunkpos= yythunkpos84;  if (!yy_AND(yy)) goto l86;  if (!yy_action(yy)) goto l86;  yyDo(yy, yy_2_prefix, yy->_begin, yy->_end);  goto l84;
  l86:;	  yy->_pos= yypos84; yy->_thunkpos= yythunkpos84;  if (!yy_AND(yy)) goto l87;  if (!yy_suffix(yy)) goto l87;  yyDo(yy, yy_3_prefix, yy->_begin, yy->_end);  goto l84;
  l87:;	  yy->_pos= yypos84; yy->_thunkpos= yythunkpos84;  if (!yy_NOT(yy)) goto l88;  if (!yy_suffix(yy)) goto l88;  yyDo(yy, yy_4_prefix, yy->_begin, yy->_end);  goto l84;
  l88:;	  yy->_pos= yypos84; yy->_thunkpos= yythunkpos84;  if (!yy_suffix(yy)) goto l83;
  }
  l84:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "prefix", yy->_buf+yy->_pos));
  return 1;
  l83:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "prefix", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_error(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "error"));  if (!yy_prefix(yy)) goto l89;
  {  int yypos90= yy->_pos, yythunkpos90= yy->_thunkpos;  if (!yy_TILDE(yy)) goto l90;  if (!yy_action(yy)) goto l90;  yyDo(yy, yy_1_error, yy->_begin, yy->_end);  goto l91;
  l90:;	  yy->_pos= yypos90; yy->_thunkpos= yythunkpos90;
  }
  l91:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "error", yy->_buf+yy->_pos));
  return 1;
  l89:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "error", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_BAR(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "BAR"));  if (!yymatchChar(yy, '|')) goto l92;  if (!yy_(yy)) goto l92;
  yyprintf((stderr, "  ok   %s @ %s\n", "BAR", yy->_buf+yy->_pos));
  return 1;
  l92:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BAR", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_sequence(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "sequence"));  if (!yy_error(yy)) goto l93;
  l94:;	
  {  int yypos95= yy->_pos, yythunkpos95= yy->_thunkpos;  if (!yy_error(yy)) goto l95;  yyDo(yy, yy_1_sequence, yy->_begin, yy->_end);  goto l94;
  l95:;	  yy->_pos= yypos95; yy->_thunkpos= yythunkpos95;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "sequence", yy->_buf+yy->_pos));
  return 1;
  l93:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sequence", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_SEMICOLON(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "SEMICOLON"));  if (!yymatchChar(yy, ';')) goto l96;  if (!yy_(yy)) goto l96;
  yyprintf((stderr, "  ok   %s @ %s\n", "SEMICOLON", yy->_buf+yy->_pos));
  return 1;
  l96:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEMICOLON", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_expression(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "expression"));  if (!yy_sequence(yy)) goto l97;
  l98:;	
  {  int yypos99= yy->_pos, yythunkpos99= yy->_thunkpos;  if (!yy_BAR(yy)) goto l99;  if (!yy_sequence(yy)) goto l99;  yyDo(yy, yy_1_expression, yy->_begin, yy->_end);  goto l98;
  l99:;	  yy->_pos= yypos99; yy->_thunkpos= yythunkpos99;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "expression", yy->_buf+yy->_pos));
  return 1;
  l97:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expression", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_EQUAL(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "EQUAL"));  if (!yymatchChar(yy, '=')) goto l100;  if (!yy_(yy)) goto l100;
  yyprintf((stderr, "  ok   %s @ %s\n", "EQUAL", yy->_buf+yy->_pos));
  return 1;
  l100:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EQUAL", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_identifier(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l101;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l101;
  l102:;	
  {  int yypos103= yy->_pos, yythunkpos103= yy->_thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l103;  goto l102;
  l103:;	  yy->_pos= yypos103; yy->_thunkpos= yythunkpos103;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l101;
#undef yytext
#undef yyleng
  }  if (!yy_(yy)) goto l101;
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yy->_buf+yy->_pos));
  return 1;
  l101:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_RPERCENT(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "RPERCENT"));  if (!yymatchString(yy, "%}")) goto l104;  if (!yy_(yy)) goto l104;
  yyprintf((stderr, "  ok   %s @ %s\n", "RPERCENT", yy->_buf+yy->_pos));
  return 1;
  l104:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RPERCENT", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_end_of_line(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "end_of_line"));
  {  int yypos106= yy->_pos, yythunkpos106= yy->_thunkpos;  if (!yymatchString(yy, "\r\n")) goto l107;  goto l106;
  l107:;	  yy->_pos= yypos106; yy->_thunkpos= yythunkpos106;  if (!yymatchChar(yy, '\n')) goto l108;  goto l106;
  l108:;	  yy->_pos= yypos106; yy->_thunkpos= yythunkpos106;  if (!yymatchChar(yy, '\r')) goto l105;
  }
  l106:;	  yyDo(yy, yy_1_end_of_line, yy->_begin, yy->_end);
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_line", yy->_buf+yy->_pos));
  return 1;
  l105:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_line", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_end_of_file(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "end_of_file"));
  {  int yypos110= yy->_pos, yythunkpos110= yy->_thunkpos;  int yymaxpos110= yy->_maxpos;  if (!yymatchDot(yy)) goto l110;  yy->_maxpos= yymaxpos110;  goto l109;
  l110:;	  yy->_pos= yypos110; yy->_thunkpos= yythunkpos110;  yy->_maxpos= yymaxpos110;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_file", yy->_buf+yy->_pos));
  return 1;
  l109:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_file", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_trailer(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "trailer"));  if (!yymatchString(yy, "%%")) goto l111;  yyDo(yy, yy_1_trailer, yy->_begin, yy->_end);  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l111;
#undef yytext
#undef yyleng
  }
  l112:;	
  {  int yypos113= yy->_pos, yythunkpos113= yy->_thunkpos;  if (!yymatchDot(yy)) goto l113;  goto l112;
  l113:;	  yy->_pos= yypos113; yy->_thunkpos= yythunkpos113;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l111;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_trailer, yy->_begin, yy->_end);
  yyprintf((stderr, "  ok   %s @ %s\n", "trailer", yy->_buf+yy->_pos));
  return 1;
  l111:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "trailer", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_definition(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "definition"));  if (!yy_identifier(yy)) goto l114;  yyDo(yy, yy_1_definition, yy->_begin, yy->_end);  if (!yy_EQUAL(yy)) goto l114;  if (!yy_expression(yy)) goto l114;  yyDo(yy, yy_2_definition, yy->_begin, yy->_end);
  {  int yypos115= yy->_pos, yythunkpos115= yy->_thunkpos;  if (!yy_SEMICOLON(yy)) goto l115;  goto l116;
  l115:;	  yy->_pos= yypos115; yy->_thunkpos= yythunkpos115;
  }
  l116:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "definition", yy->_buf+yy->_pos));
  return 1;
  l114:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "definition", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_declaration(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "declaration"));  if (!yymatchString(yy, "%{")) goto l117;  yyDo(yy, yy_1_declaration, yy->_begin, yy->_end);  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_BEGIN)) goto l117;
#undef yytext
#undef yyleng
  }
  l118:;	
  {  int yypos119= yy->_pos, yythunkpos119= yy->_thunkpos;
  {  int yypos120= yy->_pos, yythunkpos120= yy->_thunkpos;  int yymaxpos120= yy->_maxpos;  if (!yymatchString(yy, "%}")) goto l120;  yy->_maxpos= yymaxpos120;  goto l119;
  l120:;	  yy->_pos= yypos120; yy->_thunkpos= yythunkpos120;  yy->_maxpos= yymaxpos120;
  }
  {  int yypos121= yy->_pos, yythunkpos121= yy->_thunkpos;  if (!yy_end_of_line(yy)) goto l122;  goto l121;
  l122:;	  yy->_pos= yypos121; yy->_thunkpos= yythunkpos121;  if (!yymatchDot(yy)) goto l119;
  }
  l121:;	  goto l118;
  l119:;	  yy->_pos= yypos119; yy->_thunkpos= yythunkpos119;
  }  yyText(yy, yy->_begin, yy->_end);  {
#define yytext yy->_text
#define yyleng yy->_textlen
if (!(YY_END)) goto l117;
#undef yytext
#undef yyleng
  }  if (!yy_RPERCENT(yy)) goto l117;  yyDo(yy, yy_2_declaration, yy->_begin, yy->_end);
  yyprintf((stderr, "  ok   %s @ %s\n", "declaration", yy->_buf+yy->_pos));
  return 1;
  l117:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "declaration", yy->_buf+yy->_pos));
  return 0;
}
YY_RULE(int) yy_(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l124:;	
  {  int yypos125= yy->_pos, yythunkpos125= yy->_thunkpos;
  {  int yypos126= yy->_pos, yythunkpos126= yy->_thunkpos;  if (!yy_space(yy)) goto l127;  goto l126;
  l127:;	  yy->_pos= yypos126; yy->_thunkpos= yythunkpos126;  if (!yy_comment(yy)) goto l125;
  }
  l126:;	  goto l124;
  l125:;	  yy->_pos= yypos125; yy->_thunkpos= yythunkpos125;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->_buf+yy->_pos));
  return 1;
}
YY_RULE(int) yy_grammar(yycontext *yy)
{  int yypos0= yy->_pos, yythunkpos0= yy->_thunkpos;
  yyprintf((stderr, "%s\n", "grammar"));  if (!yy_(yy)) goto l128;
  {  int yypos131= yy->_pos, yythunkpos131= yy->_thunkpos;  if (!yy_declaration(yy)) goto l132;  goto l131;
  l132:;	  yy->_pos= yypos131; yy->_thunkpos= yythunkpos131;  if (!yy_definition(yy)) goto l128;
  }
  l131:;	
  l129:;	
  {  int yypos130= yy->_pos, yythunkpos130= yy->_thunkpos;
  {  int yypos133= yy->_pos, yythunkpos133= yy->_thunkpos;  if (!yy_declaration(yy)) goto l134;  goto l133;
  l134:;	  yy->_pos= yypos133; yy->_thunkpos= yythunkpos133;  if (!yy_definition(yy)) goto l130;
  }
  l133:;	  goto l129;
  l130:;	  yy->_pos= yypos130; yy->_thunkpos= yythunkpos130;
  }
  {  int yypos135= yy->_pos, yythunkpos135= yy->_thunkpos;  if (!yy_trailer(yy)) goto l135;  goto l136;
  l135:;	  yy->_pos= yypos135; yy->_thunkpos= yythunkpos135;
  }
  l136:;	  if (!yy_end_of_file(yy)) goto l128;
  yyprintf((stderr, "  ok   %s @ %s\n", "grammar", yy->_buf+yy->_pos));
  return 1;
  l128:;	  yy->_pos= yypos0; yy->_thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "grammar", yy->_buf+yy->_pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->_buflen)
    {
      yyctx->_buflen= YY_BUFFER_SIZE;
      yyctx->_buf= (char *)YY_MALLOC(yyctx, yyctx->_buflen);
      yyctx->_textlen= YY_BUFFER_SIZE;
      yyctx->_text= (char *)YY_MALLOC(yyctx, yyctx->_textlen);
      yyctx->_thunkslen= YY_STACK_SIZE;
      yyctx->_thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->_thunkslen);
#ifdef __cplusplus
      yyctx->_vals = new std::vector<YYSTYPE>();
      yyctx->_vals->reserve(YY_STACK_SIZE);
#else
      yyctx->_valslen= YY_STACK_SIZE;
      yyctx->_vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->_valslen);
      memset(yyctx->_vals, 0, sizeof(YYSTYPE) * yyctx->_valslen);
#endif
      yyctx->_begin= yyctx->_end= yyctx->_pos= yyctx->_limit= yyctx->_maxpos= yyctx->_thunkpos= 0;
    }
  yyctx->_begin= yyctx->_end= yyctx->_pos;
  yyctx->_thunkpos= 0;
#ifdef __cplusplus
  yyctx->_vals->resize(1);
  yyctx->_val = &yyctx->_vals->back();
#else
  yyctx->_val= yyctx->_vals;
#endif
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_grammar);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->_buflen)
    {
      yyctx->_buflen= 0;
      YY_FREE(yyctx, yyctx->_buf);
      YY_FREE(yyctx, yyctx->_text);
      YY_FREE(yyctx, yyctx->_thunks);
#ifdef __cplusplus
      delete yyctx->_vals;
#else
      YY_FREE(yyctx, yyctx->_vals);
#endif
    }
  return yyctx;
}

#endif
#line 163 "src/leg.leg"


void yyerror(char *message)
{
  fprintf(stderr, "%s:%d: %s", fileName, lineNumber, message);
  if (yyctx->_text[0]) fprintf(stderr, " near token '%s'", yyctx->_text);
  if (yyctx->_pos < yyctx->_limit || !feof(input))
    {
      yyctx->_buf[yyctx->_limit]= '\0';
      fprintf(stderr, " before text \"");
      while (yyctx->_pos < yyctx->_limit)
	{
	  if ('\n' == yyctx->_buf[yyctx->_pos] || '\r' == yyctx->_buf[yyctx->_pos]) break;
	  fputc(yyctx->_buf[yyctx->_pos++], stderr);
	}
      if (yyctx->_pos == yyctx->_limit)
	{
	  int c;
	  while (EOF != (c= fgetc(input)) && '\n' != c && '\r' != c)
	    fputc(c, stderr);
	}
      fputc('\"', stderr);
    }
  fprintf(stderr, "\n");
  exit(1);
}

void makeHeader(int line, char *text)
{
  Header *header= (Header *)malloc(sizeof(Header));
  header->line= line;
  header->text= strdup(text);
  header->next= headers;
  headers= header;
}

void makeTrailer(int line, char *text)
{
  trailerLine= line;
  trailer= strdup(text);
}

static void version(char *name)
{
  printf("%s version %d.%d.%d\n", name, PEG_MAJOR, PEG_MINOR, PEG_LEVEL);
}

static void usage(char *name)
{
  version(name);
  fprintf(stderr, "usage: %s [<option>...] [<file>...]\n", name);
  fprintf(stderr, "where <option> can be\n");
  fprintf(stderr, "  -h          print this help information\n");
  fprintf(stderr, "  -o <ofile>  write output to <ofile>\n");
  fprintf(stderr, "  -P          do not generate #line directives\n");
  fprintf(stderr, "  -v          be verbose\n");
  fprintf(stderr, "  -V          print version number and exit\n");
  fprintf(stderr, "if no <file> is given, input is read from stdin\n");
  fprintf(stderr, "if no <ofile> is given, output is written to stdout\n");
  exit(1);
}

int main(int argc, char **argv)
{
  Node *n;
  int   c;

  output= stdout;
  input= stdin;
  lineNumber= 1;
  fileName= "<stdin>";

  while (-1 != (c= getopt(argc, argv, "PVho:v")))
    {
      switch (c)
	{
	case 'V':
	  version(basename(argv[0]));
	  exit(0);

	case 'h':
	  usage(basename(argv[0]));
	  break;

	case 'o':
	  if (!(output= fopen(optarg, "w")))
	    {
	      perror(optarg);
	      exit(1);
	    }
	  break;

	case 'P':
	  nolinesFlag= 1;
	  break;

	case 'v':
	  verboseFlag= 1;
	  break;

	default:
	  fprintf(stderr, "for usage try: %s -h\n", argv[0]);
	  exit(1);
	}
    }
  argc -= optind;
  argv += optind;

  if (argc)
    {
      for (;  argc;  --argc, ++argv)
	{
	  if (!strcmp(*argv, "-"))
	    {
	      input= stdin;
	      fileName= "<stdin>";
	    }
	  else
	    {
	      if (!(input= fopen(*argv, "r")))
		{
		  perror(*argv);
		  exit(1);
		}
	      fileName= *argv;
	    }
	  lineNumber= 1;
	  if (!yyparse())
	    yyerror("syntax error");
	  if (input != stdin)
	    fclose(input);
	}
    }
  else
    if (!yyparse())
      yyerror("syntax error");

  if (verboseFlag)
    for (n= rules;  n;  n= n->any.next)
      Rule_print(n);

  Rule_compile_c_header();

  for (; headers;  headers= headers->next) {
    if (!nolinesFlag)
      fprintf(output, "#line %i \"%s\"\n", headers->line, fileName);
    fprintf(output, "%s\n", headers->text);
  }
  
  if (rules)
    Rule_compile_c(rules, nolinesFlag);

  if (trailer) {
    if (!nolinesFlag)
      fprintf(output, "#line %i \"%s\"\n", trailerLine, fileName);
    fprintf(output, "%s\n", trailer);
  }

  return 0;
}

